<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="right-part">
      <div class="logo"><a href="/"><img src="theme/images/logo.png" alt=""/></a></div>
      <p class="copy">&copy;2015 DROV, Inc. All Rights Reserved </p>
    </div>
    <div class="left-part">
      <div class="location"><a href="#">13832 Wireless Way, Suite 100, Oklahoma City, OK 73134 </a></div>
      <div class="phone">Office <a href="tel:4054636562">405.463.6562</a>  Mobile <a href="tel:2037038132">203.703.8132</a></div>
      <div class="mail"><a href="mailto:joe_cappello@drovtechnologies.com">joe_cappello@drovtechnologies.com</a></div>
    </div>
  </div>
</footer>