<header id="site-header" class="site-header">
  <div class="container">
    <div class="logo"><a href="/"><img src="theme/images/logo.png" alt=""/></a></div>
    
    <div class="btn-nav"><a href="#"></a></div>
    <div class="navigation">
      <div class="top-menu">
        <ul class="menu">
          <li><a href="#">Tire Pressure Management </a></li>
          <li><a href="#">AirBoxOne™</a></li>
          <li><a href="#">Analytics & IoT</a></li>
        </ul>
        <div class="btn-wrap"><a href="#" class="btn-login">LOGIN</a></div>
      </div>
      <nav class="bottom-menu">
        <ul>
          <li><a href="#">Who We Are</a></li>
          <li><a href="#">Sustainability</a></li>
          <li><a href="#">Technology</a></li>
          <li><a href="#">Careers</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </nav>
    </div>
  </div>
</header>